spawn_npc(npc = Npcs.BANKER, x = 3166, z = 3490, direction = Direction.EAST)
spawn_npc(npc = Npcs.BANKER, x = 3166, z = 3489, direction = Direction.EAST)
spawn_npc(npc = Npcs.BANKER, x = 3163, z = 3490, direction = Direction.WEST)
spawn_npc(npc = Npcs.BANKER, x = 3163, z = 3489, direction = Direction.WEST)

spawn_npc(npc = Npcs.GRAND_EXCHANGE_CLERK, x = 3165, z = 3488, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GRAND_EXCHANGE_CLERK, x = 3164, z = 3488, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GRAND_EXCHANGE_CLERK, x = 3165, z = 3491, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GRAND_EXCHANGE_CLERK, x = 3164, z = 3491, direction = Direction.NORTH)

spawn_npc(npc = Npcs.BOB_BARTER_HERBS, x = 3156, z = 3481, direction = Direction.EAST)
spawn_npc(npc = Npcs.BRUGSEN_BURSEN, x = 3165, z = 3477, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.FARID_MORRISANE_ORES_AND_BARS, x = 3173, z = 3498, direction = Direction.WEST)
spawn_npc(npc = Npcs.HOFUTHAND_WEAPONS_AND_ARMOUR, x = 3156, z = 3498, direction = Direction.EAST)
spawn_npc(npc = Npcs.MURKY_MATT_RUNES, x = 3173, z = 3481, direction = Direction.WEST)
spawn_npc(npc = Npcs.RELOBO_BLINYO_LOGS, x = 3152, z = 3489, direction = Direction.EAST)